SELECT ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST),2),'km') AS TOTAL_DISTANCE, 
CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY 1 DESC; /*여기서 TOTAL_DISTANCE는 CONCAT으로 인해 숫자가 아니기에 사용하지 않음*/