 SELECT DISTINCT H.CAR_ID
 FROM CAR_RENTAL_COMPANY_CAR C
 JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
 WHERE MONTH(H.START_DATE) = '10' AND C.CAR_TYPE = '세단'
 ORDER BY H.CAR_ID DESC;