SELECT SUM(G.SCORE) AS SCORE , E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
JOIN HR_DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
WHERE G.YEAR = 2022
GROUP BY E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
ORDER BY SUM(G.SCORE) DESC
LIMIT 1;